### ISSUE TITLE
julec: GCC compatibility issues

### ISSUE THREAD

**Issue by mertcandav** [the-xlang/x#34]
### Description

We tried to create a CI for Windows. It was a simple build CI. It would build JuleC from the IR code and rebuild and compile the latest JuleC from source. But we had some problems.

This CI gets the latest `windows-amd64` with CURL from Julec-IR repository and compiles via GCC with `O3`, `-w`, `-Wa,-mbig-obj` and C++17. After compiling the IR code obtained with CURL, a simple command is executed for testing. A simple `julec version` command is then executed. However, the execution of the program results in failure.

We left only the header files and an empty entry point, as we thought this could be caused by some algorithms in the IR code. Then we removed all header files. It was the inclusion of the API that was causing the problem. However, we had a program that did nothing. There was an empty entry point. From what we analyzed, the API did not have code that would lead to the execution of an algorithm that could cause problems when just included. So the program wasn't really doing anything as far as we know.

This issue could be a minor overlooked bug, a simple programming error in the API, or something that has nothing to do with us directly, such as a GCC compilation issue.  We tried to do various things to understand this problem, but we couldn't find a  rational point to start fixing it. Needs more research.

### Expected behavior

Program should execute as expected.

### Current behavior

Each execution's result is `Process completed with exit code -1073741511` or something like that.

### Additional information

The current situation when we do this:
- Commit of Jule repository: [`79c36b2e9e`](https://github.com/julelang/jule/tree/79c36b2e9e1d51df040fb1a6615de2188cc7f51a)
- Commit of Julec-IR repository: [`9ab7a750fc`](https://github.com/julelang/julec-ir/tree/9ab7a750fc79cdfbb8af849ec83dffef15d68e59)

**Comment by mertcandav** [comment]
Here is the more information about that.

We tried again to create a workflow for Windows. Meanwhile, Jule's current commit was [`512978d224`](https://github.com/julelang/jule/tree/512978d2240f4d7e141d93f589f22ec7906c635d), and IR's current commit was [`9ab7a750fc`](https://github.com/julelang/julec-ir/tree/9ab7a750fc79cdfbb8af849ec83dffef15d68e59). The attempt failed again. Again a fail exit code. This time the exit code was `1`.

Using Clang is not possible due to MSVC. Using `windows-2019` runner image did not fix the problem and caused compilation errors. `windows-latest`, which is currently `windows-2022`, can compile JuleC IR. But even a simple command `julec version` exits with code `1`. So `JuleC Version` step is failed.

We used `Wa,-mbig-obj` to avoid `File too big` problem with GCC.

Our workflow `build_windows.yml` file:
```yml
name: Build (Windows)
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get latest IR
        run: |
          curl -o .\ir.cpp https://raw.githubusercontent.com/julelang/julec-ir/main/src/windows-amd64.cpp

      - name: Compile Latest JuleC IR
        shell: cmd
        run: |
          mkdir .\bin
          g++ -Wa,-mbig-obj -O0 --std=c++17 -w -o .\bin\julec.exe .\ir.cpp
          git update-index --add --chmod=-x .\bin\julec.exe

      - name: JuleC Version
        run: |
          .\bin\julec.exe version

      - name: Build JuleC
        shell: cmd
        run: |
          .\bin\julec.exe -t .\src\julec
          g++ -Wa,-mbig-obj -O0 --std=c++17 -w -o .\bin\julec.exe .\dist\ir.cpp
          git update-index --add --chmod=-x .\bin\julec.exe
```


We tried this with same JuleC codes and IR on our `amd64` machine running Windows 10 and the compiler compiled from IR worked as expected. We still don't have clear data on why GitHub Actions build is problematic.

Additionally, on our own machine, GCC does not have a `File too big` problem, so we were able to compile without using `Wa,-mbig-obj`.
